# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

last_5_commits = changelog_from_git_commits(pretty:" - %s [%aN]", commits_count:5)

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do
    build

    firebase_app_distribution(
        app: "1:263329569205:android:3b6726d7d43a50ccabe1fc",
        groups: "internal",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        release_notes: last_5_commits
    )
  end

  desc "Build"
  lane :build do
    gradle(task: "clean assembleRelease")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store
  end
end
