# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

last_5_commits = changelog_from_git_commits(pretty:" - %s [%aN]", commits_count:5)

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do
    build

    firebase_app_distribution(
        app: "1:263329569205:android:ff79279a2ce9141aabe1fc",
        groups: "internal",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        release_notes: last_5_commits
    )
  end

  desc "Build"
  lane :build do
    gradle(task: "clean assembleRelease")

    gradle(
       task: "bundle",
       build_type: "Release",
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    versions = google_play_track_version_codes(track: "production")
    version_code = versions[0] + 1

    upload_to_play_store(
       track: 'production',
#        track_promote_to: 'production',
#        skip_upload_apk: true,
       skip_upload_metadata: false,
       skip_upload_images: true,
       skip_upload_screenshots: true,
#        skip_upload_aab: true,
       aab: "../build/app/outputs/bundle/release/app-release.aab",
       version_code: version_code
    )
  end
end
